language: node_js
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - "8.4.0"
install:
  - yarn
script:
  - yarn test
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
